### ISSUE TITLE
Clang compilation issues

### ISSUE THREAD

**Issue by brbrr** [DarrenLevine/cppserdes#1]
Hi. I trying to compile the library with clang, but unfortunately, I'm running into errors.

1. `Reference to 'atomic' is ambiguous` at bitcpy_common:75
I was able to "fix" it by commenting out forward declared `std::atomic` at the beginning of the file.

2. `Variable of non-literal type 'const sized_pointer<const uint8_t>' (aka 'const sized_pointer<const unsigned char>') cannot be defined in a constexpr function`
Not sure what to do here 🤷 

Any ideas on how to properly compile it with Clang? FWIW, I'm using lasted AppleClang with XCode.

**Comment by DarrenLevine** [comment]
Hi, thanks for trying out the code!

For your first problem, I added a if `defined(__APPLE__)` check for the forward declaration of std::atomic, so it should now automatically get removed when the apple-clang compiler is used.

For your second problem, it turns out the "Non-literal variables (and labels and gotos) in constexpr functions"  feature is not supported by the apple-clang compiler: https://en.cppreference.com/w/cpp/compiler_support#cpp14

So, to fix this, I added some if `defined(__APPLE__)` clauses into the code which disables *some* constexpr features on your platform, and added a note in the readme stating that not all compilers support full constexpr use. Though note that constexpr will probably still work for you for most cases if you want to use it, just not the ones where non-literal variables are needed.

Can you give it a try when you get a chance and confirm if those changes fix your issues? I merged the changes into the main branch.

**Comment by brbrr** [comment]
Yup. Works well. Thanks!
